### PR TITLE
switch to https://schema.org/version/latest/schema.rdf

### PR DESCRIPTION
**Pull request by mr-c**
You are invited to move/donate your tool descriptions to https://github.com/common-workflow-library/bio-cwl-tools where we do this sort of maintenance collaboratively

### CODE REVIEW

**Comment by inutano** [comment]
Thanks @mr-c ! I'm happy to donate these tools. How can I manage the tool already exists in the `bio-cwl-tools`, but having a slight difference? Is it okay to overwrite keeping the backward compatibility? Also, how should I put the tool like `fastqc-util-ttl.cwl`, a converter of the FastQC output? Should I put it in `fastqc` dir, or create a directory for it?

**Comment by inutano** [comment]
I got the point - I'll add my CWL file as fastqc_3.cwl or so if I needed

**Comment by mr-c** [comment]
You are welcome @inutano !

I just added https://github.com/common-workflow-library/bio-cwl-tools#how-to-donate-your-tool-descriptions which you may find useful

**Comment by inutano** [comment]
Cool, thanks! I guess I could add `fastqc-utils` tools along with the fastqc descriptions, but let's see how it looks when it's ready. I'll send a PR!

**Pull request merged**
